services:
  golab:
    mem_limit: 2g
    build:
      context: .                  # Uses your existing Dockerfile
      dockerfile: dockerfile_go
      cache_from:
        - golang:1.25
        - alpine:3.23
    ports:
      - "8080:${APP_PORT}"               # Change if your app uses a different port
    environment:
      APP_ENV: "${APP_ENV}"
      APP_PROTOCOL: "${APP_PROTOCOL}"
      APP_HOST: "${APP_HOST}"
      APP_PORT: "${APP_PORT}"
      APP_ROOT: "${APP_ROOT}"
      APP_SERVICE_TIMEOUT: "${APP_SERVICE_TIMEOUT}"
      APP_REPO_TIMEOUT: "${APP_REPO_TIMEOUT}"
      DB_DRIVER: "${DB_DRIVER}"
      DB_DSN: "${DB_DSN}"
      AUTH_CLIENT_ID: "${AUTH_CLIENT_ID}"
      AUTH_CLIENT_SECRET: "${AUTH_CLIENT_SECRET}"
      AUTH_TOKEN_URL: "${AUTH_TOKEN_URL}"
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  mariadb:
    image: mariadb:11.8
    mem_limit: 6g
    command: >
      --innodb_buffer_pool_size=4G
      --innodb_log_file_size=512M
      --innodb_log_buffer_size=64M
      --max_connections=50
      --tmp_table_size=256M
      --max_heap_table_size=256M
    container_name: mariadb-golab
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"               # Optional: remove if you don't need host access
    healthcheck:
      test: [ "CMD", "mariadb-admin", "--protocol=tcp", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mariadb_data:
